=== mlaflamm/yamb/src/yamb/util/commands/xml/commands.dtd
<?xml version='1.0' encoding='UTF-8' ?>

<!--Generated by XML Authority-->

<!ELEMENT commands (command* , menubar* , menu* , toolbar*)>

<!ELEMENT command EMPTY>

<!ATTLIST command  id          CDATA  #REQUIRED
                     description CDATA  #IMPLIED
                     icon        CDATA  #IMPLIED
                     accelerator CDATA  #IMPLIED
                     text        CDATA  #IMPLIED
                     group       CDATA  #IMPLIED >
<!ELEMENT menubar (menu)*>

<!ATTLIST menubar  id CDATA  #REQUIRED >
<!ELEMENT menu (menu | menuItem | separator)*>

<!ATTLIST menu  id   CDATA  #IMPLIED
                  text CDATA  #IMPLIED >
<!ELEMENT menuItem EMPTY>

<!ATTLIST menuItem  ref         CDATA  #IMPLIED
                      text        CDATA  #IMPLIED
                      displayIcon  (true | false )  'false' >
<!ELEMENT separator EMPTY>

<!ELEMENT toolbar (toolbarItem | separator)*>

<!ATTLIST toolbar  id CDATA  #REQUIRED >
<!ELEMENT toolbarItem EMPTY>

<!ATTLIST toolbarItem  ref     CDATA  #IMPLIED >

=== mlaflamm/yamb/src/yamb/commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Manuel Laflamme (Java development) -->
<!DOCTYPE commands SYSTEM "../yamb/util/commands/xml/commands.dtd">
<commands>
    <!-- File commands -->
    <command id="open" description="Open file" icon="yamb/images/open.gif"
             text="#Open File..."/>
    <command id="save" description="Save file" icon="yamb/images/save.gif" accelerator="control S"
             text="#Save File As..."/>
    <command id="exportTagStats" description="Export tag statistics" icon="empty.gif"
             text="Export tag statistics..."/>
    <command id="exportPivots" description="Export Pivots collection" icon="empty.gif"
             text="Export Pivots collection..."/>
    <command id="exit" description="Quit the application" icon="yamb/images/empty.gif" accelerator="alt F4"
             text="E#xit"/>

    <command id="openStatView" description="Open a new statistics view"
             icon="yamb/images/stats.gif" text="Open #Statistics View"/>

    <!--<command id="thumbnailCacheCleanup" description="Open the selected items" icon="yamb/images/empty.gif" accelerator="control O" text="#Open"/>-->

    <!-- Navigation commands -->
    <!--
        <command id="back" icon="yamb/images/back2.gif" text="#Back"/>
        <command id="forward" icon="yamb/images/forward2.gif" text="#Forward"/>
        <command id="up" icon="yamb/images/up2.gif" text="#Up"/>
    -->
    <!-- Edit commands -->
    <!--
        <command id="undo" description="Undo the last action" icon="yamb/images/empty.gif" accelerator="control Z" text="#Undo"/>
        <command id="redo" description="Redo the previously undone action" icon="yamb/images/empty.gif" accelerator="control Y" text="#Redo"/>
        <command id="cut" description="Cut the selection and put it in the Clipboard" icon="yamb/images/cut.gif" accelerator="control X" text="Cu#t"/>
        <command id="copy" description="Copy the selection and put it in the Clipboard" icon="yamb/images/copy.gif" accelerator="control C" text="#Copy"/>
        <command id="paste" description="Insert Clipboard content" icon="yamb/images/paste.gif" accelerator="control V" text="#Paste"/>
        <command id="rename" description="Rename the selected items" icon="yamb/images/empty.gif" accelerator="F2" text="#Rename"/>
        <command id="clear" description="Deletes the selected items" icon="yamb/images/empty.gif" text="#Delete"/>
        <command id="selectAll" description="Deletes the selected items" icon="yamb/images/empty.gif" accelerator="control A" text="Select #All"/>
    -->

    <!-- File commands -->
    <command id="fileOpen" description="Open the selected items" icon="yamb/images/empty.gif" accelerator="control O"
             text="#Open"/>
    <command id="fileOpenContainingFolderInExplorer" description="Open the focused item containing folder in explorer"
             icon="yamb/images/empty.gif" text="Open Containing #Folder in Explorer"/>
    <command id="fileOpenExplorerView" description="Open the focused item folder in a new eplorer view"
             icon="yamb/images/folders2.gif" accelerator="control E" text="Open #Explorer View"/>
    <command id="fileOpenTagView" description="Open the selected items in a new tag view"
             icon="yamb/images/tags.gif" accelerator="control T" text="Open #Tag View"/>
    <command id="fileOpenGroupView" description="Open the selected item in a new file group view"
             icon="yamb/images/groups.gif" accelerator="control G" text="Open #Group View"/>
    <command id="folderOpenRecursive" description="Open the selected folder and show all children recursively"
             icon="yamb/images/empty.gif" text="Open Recursive"/>
    <command id="folderAddLibrary" description="Add the selected folder as a library"
             icon="yamb/images/empty.gif" text="Add Library"/>
    <command id="folderRemoveLibrary" description="Remove the selected folder library"
             icon="yamb/images/empty.gif" text="Remove Library"/>
    <command id="folderRebuildLibrary" description="Rebuild the selected folder library"
             icon="yamb/images/empty.gif" text="Rebuild Library"/>
    <command id="fileRebuildThumbnail" description="Regenerate the selected files thumbnails"
             icon="yamb/images/empty.gif"
             text="Rebuild T#humbnail"/>
    <command id="fileRebuildLibrary" description="Regenerate the selected files libraries" icon="yamb/images/empty.gif"
             text="Rebuild #Library"/>
    <command id="fileCut" description="Cut the selection and put it in the Clipboard" icon="yamb/images/cut.gif"
             accelerator="control X" text="Cu#t"/>
    <command id="fileCopy" description="Copy the selection and put it in the Clipboard" icon="yamb/images/copy.gif"
             accelerator="control C" text="#Copy"/>
    <command id="filePaste" description="Insert Clipboard content" icon="yamb/images/paste.gif" accelerator="control V"
             text="#Paste"/>
    <command id="fileRename" description="Rename the selected items" icon="yamb/images/empty.gif" accelerator="F2"
             text="#Rename"/>
    <command id="fileDelete" description="Deletes the selected items" icon="yamb/images/empty.gif" accelerator="DELETE"
             text="#Delete"/>
    <command id="fileSelectAll" description="Deletes the selected items" icon="yamb/images/empty.gif"
             text="Select #All"/>
    <command id="fileProperties" description="Displays the properties of the selected items"
             icon="yamb/images/empty.gif"
             text="Properties"/>
    <command id="fileFilterSelectedTags" description="Set the selected files tags as file filter"
             icon="yamb/images/tags.gif"
             text="Filter Files By Selected Tags"/>
    <command id="fileFilterSelectedFileGroups" description="Set the selected files groups as file filter"
             icon="yamb/images/groups.gif"
             text="Filter Files By Selected Groups"/>
    <command id="fileFilterReset" description="Reset the file filter" icon="yamb/images/star.gif"
             text="Filter Reset"/>

    <command id="fileTypeFilterAll" description="Shows all file items" icon="yamb/images/empty.gif"
             text="#All" group="fileTypeFilter"/>
    <command id="fileTypeFilterVideos" description="Shows only video file items" icon="yamb/images/empty.gif"
             text="#Videos" group="fileTypeFilter"/>
    <command id="fileTypeFilterImages" description="Shows only image file items" icon="yamb/images/empty.gif"
             text="#Images" group="fileTypeFilter"/>
    <command id="fileTypeFilterCustom" description="Shows file items matching the custom filter"
             icon="yamb/images/empty.gif"
             text="#Custom" group="fileTypeFilter"/>


    <!-- View commands -->
    <command id="explorerBack" icon="yamb/images/back2.gif" text="#Back"/>
    <command id="explorerForward" icon="yamb/images/forward2.gif" text="#Forward"/>
    <command id="explorerUp" icon="yamb/images/up2.gif" text="#Up"/>
    <command id="explorerShowFolders" description="Shows the folders bar" icon="yamb/images/folders.gif"
             text="#Folders"/>
    <command id="fileTypeFilterPopup" description="Select file type filter" icon="yamb/images/filter.gif"
             text="File Type Filter"/>

    <!--
        <command id="viewFavorites" description="Displays favorites browser" icon="yamb/images/favorites.gif"
                 text="Favorites" group="treeViewMode"/>
    -->

    <command id="viewList" description="Displays items in a list" icon="yamb/images/list.gif" text="#List"
             group="listViewMode"/>
    <command id="viewDetails" description="Displays detailed information about each item in the view"
             icon="yamb/images/details.gif" text="#Details" group="listViewMode"/>
    <command id="viewThumbnails" description="Displays items using thumbnail view" icon="yamb/images/thumbnails.gif"
             text="#Thumbnails" group="listViewMode"/>

    <command id="viewRefresh" description="Refreshes the content of the current view" icon="yamb/images/refresh.gif"
             accelerator="F5" text="#Refresh"/>

    <command id="tagSetAnd" description="Displays files matching all the active tags" icon="yamb/images/equal.gif"
             text="'#And' tag condition" group="tagGrouping"/>
    <command id="tagSetOr" description="Displays files matching at least one of the active tags"
             icon="yamb/images/plus.gif"
             text="'#Or' tag condition" group="tagGrouping"/>
    <command id="tagRecentOnly" description="Displays only recent tagged files" icon="yamb/images/recent.gif"
             text="Recent Only" group="tagRecentOnly"/>
    <command id="tagFilterActiveTags" description="Set the active tags as tags filter" icon="yamb/images/tags.gif"
             text="Filter Tags By Active Tags"/>
    <command id="tagFilterReset" description="Reset the tags filter" icon="yamb/images/star.gif"
             text="Filter Reset"/>

    <command id="libraryCopy" description="Copies the path of the selected libraries into the clipboards"
             icon="yamb/images/empty.gif" text="#Copy Path"/>
    <command id="libraryLoadSelected" description="Loads selected libraries"
             icon="yamb/images/empty.gif" text="Load Selected"/>
    <command id="libraryLoadSelectedOnly" description="Loads only selected libraries and unload others"
             icon="yamb/images/empty.gif" text="Load Selected Only"/>
    <command id="libraryLoadAll" description="Loads all libraries"
             icon="yamb/images/_selectall.gif" text="#Load All"/>
    <command id="libraryUnloadSelected" description="Unloads selected libraries"
             icon="yamb/images/empty.gif" text="#Unload Selected"/>
    <command id="libraryRemoveSelected" description="Remove selected libraries"
             icon="yamb/images/empty.gif" text="#Remove Selected"/>
